[workspace]

members = [
  "crates/wasm-bridge",
  "crates/wasm-bridge-js",
  "crates/wasm-bridge-macros",
  "examples/wit_components/",
  "examples/wit_components/records/",
]

exclude = [
  "tests/"
]

[workspace.package]
version = "0.2.2"
edition = "2021"
repository = "https://github.com/kajacx/wasm-bridge"
license = "MIT"
keywords = ["WASM", "wasmtime", "web"]
categories = ["wasm", "web-programming"]
