[workspace]

members = [
  "crates/wasm-bridge",
  "crates/wasm-bridge-cli",
  "crates/wasm-bridge-js",
  "crates/wasm-bridge-macros",
]

exclude = [
  "tests/"
]

[workspace.package]
version = "0.1.5"
edition = "2021"
repository = "https://github.com/kajacx/wasm-bridge"
license = "MIT"
keywords = ["WASM", "wasmtime", "web"]
categories = ["wasm", "web-programming"]
