[package]
name = "wasm-bridge-cli"
description = "Command line tool to prepare jco-transpiled components (deprecated)"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
