name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build sys
      run: cargo build --verbose
    - name: Install wasm32 target
      run: rustup target add wasm32-unknown-unknown
    - name: Build js
      run: cargo build --target wasm32-unknown-unknown --verbose
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Run tests
      run: cd tests && bash run_all_tests.sh
