[package]
name = "wasm-bridge-js"
description = "js-sys implementation of wasmtime's API"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
js-sys = { version = "0.3.64" }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = { version = "0.4.37" }
wat = { version = "1.0.66", optional = true }
wasm-bridge-macros = { path = "../wasm-bridge-macros", version = "0.1.6", optional = true }
wasm-bridge-jco = { path = "../wasm-bridge-jco", version = "0.1.6", optional = true }
anyhow = { version = "1.0.22" }
heck = { version = "0.4.1" }

[features]
component-model = ["wasm-bridge-macros", "wasm-bridge-jco"]
error-logging = []
