[package]
name = "wasm-bridge-js"
description = "js-sys implementation of wasmtime's API"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bridge-macros = { path = "../wasm-bridge-macros", optional = true }
js-sys = { version = "0.3.64" }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = { version = "0.4.37" }
anyhow = { version = "1.0.22" }
wat = { version = "1.0.66" }

[features]
component-model = ["wasm-bridge-macros"]
